version: '3.1'
services:
  app:
    container_name: demo-docker
    image: demo-docker
    build: .
    ports:
      - "8087:8087"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=webservice
